# Example configuration.yaml entry
sensor:
  - name: "Temperature"
    state_topic: "office/sensor1"
    suggested_display_precision: 1
    unit_of_measurement: "°C"
    value_template: "{{ value_json.temperature }}"
    unique_id: "dragino_temp"
  - name: "Humidity"
    state_topic: "office/sensor1"
    unit_of_measurement: "%"
    value_template: "{{ value_json.humidity }}"
    unique_id: "dragino_hum"
